---
abstract: 'Rinci/Riap-based command-line application framework'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Capture::Tiny: 0
  File::Slurp: 0
  Module::Build: 0.3601
  Test::More: 0.96
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perinci-CmdLine
requires:
  Data::Dump::OneLine: 0
  Data::Format::Pretty::Console: 0
  File::Which: 0
  JSON: 0
  Log::Any: 0
  Log::Any::App: 0
  Monkey::Patch::Action: 0
  Moo: 0
  Perinci::Access: 0.30
  Perinci::Access::HTTP::Client: 0.06
  Perinci::Access::InProcess: 0.36
  Perinci::Access::Simple::Client: 0
  Perinci::BashComplete: 0.29
  Perinci::Object: 0.11
  Perinci::Result::Format: 0.11
  Perinci::Sub::GetArgs::Argv: 0.22
  Perinci::Sub::Wrapper: 0.40
  Perinci::To::Text::AddDocLinesRole: 0.10
  Perinci::ToUtil: 0
  Perinci::Tx::Manager: 0.34
  Progress::Any: 0
  Progress::Any::Output::Null: 0
  Progress::Any::Output::TermProgressBar: 0
  Rinci: v1.1.27
  SHARYANTO::Role::Doc::Section: 0
  SHARYANTO::Role::I18N: 0
  SHARYANTO::Role::I18NRinci: 0
  Tie::Simple: 0
  UUID::Random: 0
  YAML::Syck: 0
  perl: 5.010001
resources:
  homepage: http://search.cpan.org/dist/Perinci-CmdLine/
  repository: http://github.com/sharyanto/perl-Perinci-CmdLine
version: 0.75
