---
abstract: 'Rinci/Riap-based command-line application framework'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Capture::Tiny: 0
  Data::Clone: 0
  File::Slurp: 0
  Module::Build: 0.3601
  Perinci::Examples: 0
  Test::More: 0.96
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perinci-CmdLine
requires:
  Data::Format::Pretty: 0
  Data::Format::Pretty::CompactJSON: 0
  Data::Format::Pretty::Console: 0.16
  Data::Format::Pretty::YAML: 0
  Data::Sah: 0.02
  File::Which: 0
  JSON: 0
  List::MoreUtils: 0
  Log::Any: 0
  Log::Any::App: 0
  Moo: 0
  Object::BlankStr: 0
  Perinci::Access: 0.22
  Perinci::Access::HTTP::Client: 0
  Perinci::Access::TCP::Client: 0
  Perinci::BashComplete: 0.29
  Perinci::Result::Format: 0.11
  Perinci::Sub::GetArgs::Argv: 0.19
  Perinci::Sub::Wrapper: 0.14
  Perinci::To::Text::AddDocLinesRole: 0.10
  Rinci: 1.1.21
  SHARYANTO::Role::Doc::Section: 0
  SHARYANTO::Role::I18N: 0
  SHARYANTO::Role::I18NRinci: 0
  Setup::File::Symlink: 0
  UUID::Random: 0
  YAML::Syck: 0
  perl: 5.010000
resources:
  homepage: http://search.cpan.org/dist/Perinci-CmdLine/
  repository: http://github.com/sharyanto/perl-Perinci-CmdLine
version: 0.57
