---
abstract: 'Rinci/Riap-based command-line application framework'
author:
  - 'perlancar <perlancar@cpan.org>'
build_requires:
  File::Slurp::Tiny: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Perinci::Examples: '0.32'
  Test::More: '0.98'
  Test::Perinci::CmdLine: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
  File::ShareDir::Install: '0.03'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.015, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Perinci-CmdLine
recommends:
  Perinci::Tx::Manager: '0.34'
requires:
  Data::Format::Pretty::Console: '0'
  Data::Unixish: '1.39'
  File::HomeDir: '0'
  Getopt::Long::Util: '0'
  JSON: '0'
  Locale::TextDomain::UTF8: '0'
  Log::Any: '0'
  Log::Any::App: '0'
  Monkey::Patch::Action: '0'
  Moo: '0'
  Moo::Role: '0'
  Perinci::Access: '0.30'
  Perinci::Access::HTTP::Client: '0.06'
  Perinci::Access::Perl: '0.66'
  Perinci::Access::Schemeless: '0.65'
  Perinci::Access::Simple::Client: '0'
  Perinci::CmdLine::Base: '0.30'
  Perinci::Object: '0.11'
  Perinci::Result::Format: '0.33'
  Perinci::Sub::ConvertArgs::Argv: '0'
  Perinci::Sub::Wrapper: '0.40'
  Perinci::ToUtil: '0'
  Progress::Any: '0.13'
  Progress::Any::Output: '0'
  Progress::Any::Output::TermProgressBarColor: '0.08'
  Rinci: v1.1.41
  SHARYANTO::Role::ColorTheme: '0.62'
  String::ShellQuote: '0'
  Text::ANSITable: '0.23'
  UUID::Random: '0'
  experimental: '0'
  perl: '5.010001'
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Perinci-CmdLine
  homepage: https://metacpan.org/release/Perinci-CmdLine
  repository: git://github.com/sharyanto/perl-Perinci-CmdLine.git
version: '1.32'
x_Dist_Zilla:
  perl:
    version: '5.018001'
  plugins:
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@Author::PERLANCAR/@Filter/GatherDir'
      version: '5.015'
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Author::PERLANCAR/@Filter/PruneCruft'
      version: '5.015'
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Author::PERLANCAR/@Filter/ManifestSkip'
      version: '5.015'
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Author::PERLANCAR/@Filter/MetaYAML'
      version: '5.015'
    -
      class: Dist::Zilla::Plugin::License
      name: '@Author::PERLANCAR/@Filter/License'
      version: '5.015'
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@Author::PERLANCAR/@Filter/PodCoverageTests'
      version: '5.015'
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Author::PERLANCAR/@Filter/PodSyntaxTests'
      version: '5.015'
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@Author::PERLANCAR/@Filter/ExtraTests'
      version: '5.015'
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Author::PERLANCAR/@Filter/ExecDir'
      version: '5.015'
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Author::PERLANCAR/@Filter/ShareDir'
      version: '5.015'
    -
      class: Dist::Zilla::Plugin::MakeMaker
      config:
        Dist::Zilla::Role::TestRunner:
          default_jobs: 1
      name: '@Author::PERLANCAR/@Filter/MakeMaker'
      version: '5.015'
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Author::PERLANCAR/@Filter/Manifest'
      version: '5.015'
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Author::PERLANCAR/@Filter/ConfirmRelease'
      version: '5.015'
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Author::PERLANCAR/@Filter/UploadToCPAN'
      version: '5.015'
    -
      class: Dist::Zilla::Plugin::PERLANCAR::MetaResources
      name: '@Author::PERLANCAR/PERLANCAR::MetaResources'
      version: '0.03'
    -
      class: Dist::Zilla::Plugin::CheckChangeLog
      name: '@Author::PERLANCAR/CheckChangeLog'
      version: '0.01'
    -
      class: Dist::Zilla::Plugin::CheckMetaResources
      name: '@Author::PERLANCAR/CheckMetaResources'
      version: '0.001'
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Author::PERLANCAR/MetaJSON'
      version: '5.015'
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Author::PERLANCAR/MetaConfig'
      version: '5.015'
    -
      class: Dist::Zilla::Plugin::OurDate
      name: '@Author::PERLANCAR/OurDate'
      version: '0.01'
    -
      class: Dist::Zilla::Plugin::PodWeaver
      config:
        Dist::Zilla::Plugin::PodWeaver:
          finder:
            - ':InstallModules'
            - ':ExecFiles'
          plugins:
            -
              class: Pod::Weaver::Plugin::EnsurePod5
              name: '@CorePrep/EnsurePod5'
              version: '4.006'
            -
              class: Pod::Weaver::Plugin::H1Nester
              name: '@CorePrep/H1Nester'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Name
              name: '@Author::PERLANCAR/Name'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Version
              name: '@Author::PERLANCAR/Version'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Region
              name: '@Author::PERLANCAR/prelude'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Generic
              name: SYNOPSIS
              version: '4.006'
            -
              class: Pod::Weaver::Section::Generic
              name: DESCRIPTION
              version: '4.006'
            -
              class: Pod::Weaver::Section::Generic
              name: OVERVIEW
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: ATTRIBUTES
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: METHODS
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: FUNCTIONS
              version: '4.006'
            -
              class: Pod::Weaver::Plugin::Perinci
              name: '@Author::PERLANCAR/Perinci'
              version: '0.15'
            -
              class: Pod::Weaver::Section::Leftovers
              name: '@Author::PERLANCAR/Leftovers'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Region
              name: '@Author::PERLANCAR/postlude'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Homepage::DefaultCPAN
              name: '@Author::PERLANCAR/Homepage::DefaultCPAN'
              version: '0.02'
            -
              class: Pod::Weaver::Section::Source::DefaultGitHub
              name: '@Author::PERLANCAR/Source::DefaultGitHub'
              version: '0.04'
            -
              class: Pod::Weaver::Section::Bugs::DefaultRT
              name: '@Author::PERLANCAR/Bugs::DefaultRT'
              version: '0.03'
            -
              class: Pod::Weaver::Section::Authors
              name: '@Author::PERLANCAR/Authors'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Legal
              name: '@Author::PERLANCAR/Legal'
              version: '4.006'
            -
              class: Pod::Weaver::Plugin::EnsureUniqueSections
              name: '@Author::PERLANCAR/EnsureUniqueSections'
              version: '0.121550'
            -
              class: Pod::Weaver::Plugin::SingleEncoding
              name: '@Author::PERLANCAR/SingleEncoding'
              version: '4.006'
      name: '@Author::PERLANCAR/PodWeaver'
      version: '4.005'
    -
      class: Dist::Zilla::Plugin::PruneFiles
      name: '@Author::PERLANCAR/PruneFiles'
      version: '5.015'
    -
      class: Dist::Zilla::Plugin::ReadmeFromPod
      name: '@Author::PERLANCAR/ReadmeFromPod'
      version: '0.21'
    -
      class: Dist::Zilla::Plugin::Rinci::Validate
      name: '@Author::PERLANCAR/Rinci::Validate'
      version: '0.15'
    -
      class: Dist::Zilla::Plugin::SetScriptShebang
      name: '@Author::PERLANCAR/SetScriptShebang'
      version: '0.01'
    -
      class: Dist::Zilla::Plugin::PERLANCAR::OurPkgVersion
      name: '@Author::PERLANCAR/PERLANCAR::OurPkgVersion'
      version: '0.03'
    -
      class: Dist::Zilla::Plugin::Test::Compile
      config:
        Dist::Zilla::Plugin::Test::Compile:
          filename: t/00-compile.t
          module_finder:
            - ':InstallModules'
          script_finder:
            - ':ExecFiles'
      name: '@Author::PERLANCAR/Test::Compile'
      version: '2.039'
    -
      class: Dist::Zilla::Plugin::Test::Rinci
      name: '@Author::PERLANCAR/Test::Rinci'
      version: '0.01'
    -
      class: Dist::Zilla::Plugin::LocaleTextDomain
      name: LocaleTextDomain
      version: '0.87'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: test
          type: requires
      name: TestRequires
      version: '5.015'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereqs
      version: '5.015'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: recommends
      name: RuntimeRecommends
      version: '5.015'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: '5.015'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: '5.015'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: '5.015'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: '5.015'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: '5.015'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: '5.015'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':AllFiles'
      version: '5.015'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':NoFiles'
      version: '5.015'
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: '0'
    version: '5.015'
